ERROR - 2024-03-18 04:33:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.8\app\Controllers\Books.php(44): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(932): App\Controllers\Books->listBooks()
#8 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgniter4-4.3.8\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.8\app\Controllers\Books.php(44): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(932): App\Controllers\Books->listBooks()
#7 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#8 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CodeIgniter4-4.3.8\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2024-03-18 04:33:41 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Books.php(44): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
ERROR - 2024-03-18 04:34:35 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\BaseModel.php(698): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.8\app\Controllers\Books.php(29): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(932): App\Controllers\Books->addBook()
#10 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4-4.3.8\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\BaseModel.php(698): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.8\app\Controllers\Books.php(29): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(932): App\Controllers\Books->addBook()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.8\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-18 04:34:35 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`title`, `category`, `isbn`, `author`, `cover_image`, `book_file`) VALUES (:title:, :category:, :isbn:, :author:, :cover_image:, :book_file:)', [...], false)
 3 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(698): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Books.php(29): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->addBook()
 9 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
10 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
ERROR - 2024-03-18 04:37:57 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'wse2' in C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'wse2', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\BaseModel.php(698): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.8\app\Controllers\Books.php(29): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(932): App\Controllers\Books->addBook()
#10 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4-4.3.8\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'wse2' in C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\BaseModel.php(698): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.8\app\Controllers\Books.php(29): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(932): App\Controllers\Books->addBook()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.8\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-18 04:37:57 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'wse2'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`title`, `category`, `isbn`, `author`, `cover_image`, `book_file`) VALUES (:title:, :category:, :isbn:, :author:, :cover_image:, :book_file:)', [...], false)
 3 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(698): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Books.php(29): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->addBook()
 9 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
10 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
ERROR - 2024-03-18 04:38:22 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'wse2' in C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'wse2', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\BaseModel.php(698): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.8\app\Controllers\Books.php(29): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(932): App\Controllers\Books->addBook()
#10 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CodeIgniter4-4.3.8\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'wse2' in C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#3 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\BaseModel.php(698): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\CodeIgniter4-4.3.8\app\Controllers\Books.php(29): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(932): App\Controllers\Books->addBook()
#9 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CodeIgniter4-4.3.8\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CodeIgniter4-4.3.8\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-18 04:38:22 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'wse2'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`title`, `category`, `isbn`, `author`, `cover_image`, `book_file`) VALUES (:title:, :category:, :isbn:, :author:, :cover_image:, :book_file:)', [...], false)
 3 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(698): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Books.php(29): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->addBook()
 9 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
10 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:38:54 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:41:35 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:43:08 --> Invalid file: "listBooks.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('listBooks.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('listBooks', [], true)
 3 APPPATH\Controllers\Books.php(46): view('listBooks', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:43:09 --> Invalid file: "listBooks.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('listBooks.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('listBooks', [], true)
 3 APPPATH\Controllers\Books.php(46): view('listBooks', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:43:09 --> Invalid file: "listBooks.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('listBooks.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('listBooks', [], true)
 3 APPPATH\Controllers\Books.php(46): view('listBooks', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:43:13 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:43:13 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:43:13 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:43:14 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:43:14 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:43:14 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:43:19 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:43:54 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:43:55 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:43:55 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:43:55 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:44:36 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:44:37 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:44:37 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:44:37 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:44:41 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
CRITICAL - 2024-03-18 04:45:57 --> Invalid file: "list_books.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('list_books.php')
 2 SYSTEMPATH\Common.php(1174): CodeIgniter\View\View->render('list_books', [], true)
 3 APPPATH\Controllers\Books.php(46): view('list_books', [...])
 4 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Books->listBooks()
 5 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\CodeIgniter4-4.3.8\\public\\index.php')
